name: Generate data and gh-pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup
      run: |
        make setup
    - name: Make data
      run: |
        make all
    - name: Finalization
      run: |
        make finalization
    - name: Deploy to gh-pages
      run: |
        make gh-pages
    #- name: Deploy
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./www/
